In [12]:
import numpy as np

# Create matrices
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])


In [13]:
# Matrix addition
C = A + B
print("Matrix Addition:")
print(C)

Matrix Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [14]:
# Matrix subtraction
D = A - B
print("Matrix Subtraction:")
print(D)


Matrix Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [15]:
# Matrix multiplication (element-wise)
E = A * B
print("Element-wise Matrix Multiplication:")
print(E)

Element-wise Matrix Multiplication:
[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [16]:
# Matrix multiplication (dot product)
F = np.dot(A, B)
print("Matrix Dot Product:")
print(F)

Matrix Dot Product:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [17]:
# Transpose of a matrix
A_transpose = A.T
print("Transpose of Matrix A:")
print(A_transpose)

Transpose of Matrix A:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [18]:
# Determinant of a matrix
det_A = np.linalg.det(A)
print("Determinant of Matrix A:", det_A)

Determinant of Matrix A: 0.0


In [19]:
# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:")
print(eigenvectors)

Eigenvalues: [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]
Eigenvectors:
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]
